<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyName>ObservatoryPhotographer</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup>
    <VersionSuffix>1.1.0.$([System.DateTime]::UtcNow.DayOfYear.ToString().PadLeft(3, "0"))$([System.DateTime]::UtcNow.Hour)</VersionSuffix>
    <AssemblyVersion Condition=" '$(VersionSuffix)' == '' ">0.0.0.1</AssemblyVersion>
    <AssemblyVersion Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</AssemblyVersion>
    <Version Condition=" '$(VersionSuffix)' == '' ">0.0.1.0</Version>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-x64" Version="14.14.0" />
  </ItemGroup>

  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Condition=" '$(OS)' == 'Windows_NT' " Command="powershell -command &quot;Get-ChildItem -Path '$(TargetDir)runtimes' -Directory -Exclude 'win-x64' | Remove-Item -Recurse -Force&quot;" />
    <Exec Condition=" '$(OS)' == 'Windows_NT' " Command="xcopy &quot;$(TargetDir)*&quot; &quot;$(ProjectDir)..\ObservatoryCore\ObservatoryCore\$(OutDir)plugins\ObservatoryPhotographer\&quot; /y /s /exclude:$(ProjectDir)xcopyExclude" />
  </Target>

  <ItemGroup>
    <Reference Include="ObservatoryFramework">
      <HintPath>..\ObservatoryCore\ObservatoryFramework\bin\Release\net8.0\ObservatoryFramework.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
