<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWindowsForms>true</UseWindowsForms>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<AssemblyName>ObservatoryPhotographer</AssemblyName>
	<PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-x64" Version="14.8.2" />
  </ItemGroup>

	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

  <ItemGroup>
    <Reference Include="ObservatoryFramework">
      <HintPath>..\ObservatoryCore\ObservatoryFramework\bin\Release\net8.0\ObservatoryFramework.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
